/**
 * SpacetimeTableStates - Type definition for all gameplay tables.
 * Used for documentation and type checking; consumers read via engine selectors.
 */
import type * as SpacetimeDB from '../../generated/types';
import type { RangedWeaponStats, Projectile } from '../../generated/types';
import type { Identity } from 'spacetimedb';

export interface SpacetimeTableStates {
  players: Map<string, SpacetimeDB.Player>;
  trees: Map<string, SpacetimeDB.Tree>;
  stones: Map<string, SpacetimeDB.Stone>;
  runeStones: Map<string, SpacetimeDB.RuneStone>;
  cairns: Map<string, SpacetimeDB.Cairn>;
  playerDiscoveredCairns: Map<string, SpacetimeDB.PlayerDiscoveredCairn>;
  campfires: Map<string, SpacetimeDB.Campfire>;
  furnaces: Map<string, SpacetimeDB.Furnace>;
  barbecues: Map<string, SpacetimeDB.Barbecue>;
  lanterns: Map<string, SpacetimeDB.Lantern>;
  turrets: Map<string, SpacetimeDB.Turret>;
  homesteadHearths: Map<string, SpacetimeDB.HomesteadHearth>;
  brothPots: Map<string, SpacetimeDB.BrothPot>;
  harvestableResources: Map<string, SpacetimeDB.HarvestableResource>;
  itemDefinitions: Map<string, SpacetimeDB.ItemDefinition>;
  inventoryItems: Map<string, SpacetimeDB.InventoryItem>;
  worldState: SpacetimeDB.WorldState | null;
  activeEquipments: Map<string, SpacetimeDB.ActiveEquipment>;
  droppedItems: Map<string, SpacetimeDB.DroppedItem>;
  woodenStorageBoxes: Map<string, SpacetimeDB.WoodenStorageBox>;
  stashes: Map<string, SpacetimeDB.Stash>;
  rainCollectors: Map<string, SpacetimeDB.RainCollector>;
  waterPatches: Map<string, SpacetimeDB.WaterPatch>;
  fertilizerPatches: Map<string, SpacetimeDB.FertilizerPatch>;
  firePatches: Map<string, SpacetimeDB.FirePatch>;
  placedExplosives: Map<string, SpacetimeDB.PlacedExplosive>;
  hotSprings: Map<string, unknown>;
  recipes: Map<string, SpacetimeDB.Recipe>;
  craftingQueueItems: Map<string, SpacetimeDB.CraftingQueueItem>;
  messages: Map<string, SpacetimeDB.Message>;
  playerPins: Map<string, SpacetimeDB.PlayerPin>;
  activeConnections: Map<string, SpacetimeDB.ActiveConnection>;
  sleepingBags: Map<string, SpacetimeDB.SleepingBag>;
  playerCorpses: Map<string, SpacetimeDB.PlayerCorpse>;
  activeConsumableEffects: Map<string, SpacetimeDB.ActiveConsumableEffect>;
  localPlayerRegistered: boolean;
  clouds: Map<string, SpacetimeDB.Cloud>;
  grass: Map<string, SpacetimeDB.Grass>;
  grassState: Map<string, SpacetimeDB.GrassState>;
  knockedOutStatus: Map<string, SpacetimeDB.KnockedOutStatus>;
  rangedWeaponStats: Map<string, RangedWeaponStats>;
  projectiles: Map<string, Projectile>;
  deathMarkers: Map<string, SpacetimeDB.DeathMarker>;
  shelters: Map<string, SpacetimeDB.Shelter>;
  minimapCache: SpacetimeDB.MinimapCache | null;
  playerDodgeRollStates: Map<string, SpacetimeDB.PlayerDodgeRollState>;
  fishingSessions: Map<string, SpacetimeDB.FishingSession>;
  plantedSeeds: Map<string, SpacetimeDB.PlantedSeed>;
  soundEvents: Map<string, SpacetimeDB.SoundEvent>;
  continuousSounds: Map<string, SpacetimeDB.ContinuousSound>;
  localPlayerIdentity: Identity | null;
  playerDrinkingCooldowns: Map<string, SpacetimeDB.PlayerDrinkingCooldown>;
  wildAnimals: Map<string, SpacetimeDB.WildAnimal>;
  hostileDeathEvents: Array<{ id: string; x: number; y: number; species: string; timestamp: number }>;
  animalCorpses: Map<string, SpacetimeDB.AnimalCorpse>;
  barrels: Map<string, SpacetimeDB.Barrel>;
  roadLampposts: Map<string, SpacetimeDB.RoadLamppost>;
  seaStacks: Map<string, SpacetimeDB.SeaStack>;
  fumaroles: Map<string, SpacetimeDB.Fumarole>;
  basaltColumns: Map<string, SpacetimeDB.BasaltColumn>;
  foundationCells: Map<string, SpacetimeDB.FoundationCell>;
  wallCells: Map<string, SpacetimeDB.WallCell>;
  doors: Map<string, SpacetimeDB.Door>;
  fences: Map<string, SpacetimeDB.Fence>;
  chunkWeather: Map<string, unknown>;
  alkStations: Map<string, SpacetimeDB.AlkStation>;
  alkContracts: Map<string, SpacetimeDB.AlkContract>;
  alkPlayerContracts: Map<string, SpacetimeDB.AlkPlayerContract>;
  alkState: SpacetimeDB.AlkState | null;
  playerShardBalance: Map<string, SpacetimeDB.PlayerShardBalance>;
  memoryGridProgress: Map<string, SpacetimeDB.MemoryGridProgress>;
  monumentParts: Map<string, unknown>;
  largeQuarries: Map<string, unknown>;
  livingCorals: Map<string, SpacetimeDB.LivingCoral>;
  matronages: Map<string, unknown>;
  matronageMembers: Map<string, unknown>;
  matronageInvitations: Map<string, unknown>;
  matronageOwedShards: Map<string, unknown>;
  playerStats: Map<string, SpacetimeDB.PlayerStats>;
  achievementDefinitions: Map<string, SpacetimeDB.AchievementDefinition>;
  playerAchievements: Map<string, SpacetimeDB.PlayerAchievement>;
  achievementUnlockNotifications: Map<string, SpacetimeDB.AchievementUnlockNotification>;
  levelUpNotifications: Map<string, SpacetimeDB.LevelUpNotification>;
  dailyLoginNotifications: Map<string, SpacetimeDB.DailyLoginNotification>;
  progressNotifications: Map<string, SpacetimeDB.ProgressNotification>;
  comparativeStatNotifications: Map<string, SpacetimeDB.ComparativeStatNotification>;
  leaderboardEntries: Map<string, SpacetimeDB.LeaderboardEntry>;
  dailyLoginRewards: Map<string, SpacetimeDB.DailyLoginReward>;
  plantConfigDefinitions: Map<string, SpacetimeDB.PlantConfigDefinition>;
  discoveredPlants: Map<string, SpacetimeDB.PlayerDiscoveredPlant>;
  tutorialQuestDefinitions: Map<string, SpacetimeDB.TutorialQuestDefinition>;
  dailyQuestDefinitions: Map<string, SpacetimeDB.DailyQuestDefinition>;
  playerTutorialProgress: Map<string, SpacetimeDB.PlayerTutorialProgress>;
  playerDailyQuests: Map<string, SpacetimeDB.PlayerDailyQuest>;
  questCompletionNotifications: Map<string, SpacetimeDB.QuestCompletionNotification>;
  questProgressNotifications: Map<string, SpacetimeDB.QuestProgressNotification>;
  sovaQuestMessages: Map<string, SpacetimeDB.SovaQuestMessage>;
  beaconDropEvents: Map<string, SpacetimeDB.BeaconDropEvent>;
  droneEvents: Map<string, SpacetimeDB.DroneEvent>;
  caribouBreedingData: Map<string, SpacetimeDB.CaribouBreedingData>;
  walrusBreedingData: Map<string, SpacetimeDB.WalrusBreedingData>;
  caribouRutState: SpacetimeDB.CaribouRutState | null;
  walrusRutState: SpacetimeDB.WalrusRutState | null;
}
